package org.moonfin.server.core.model

data class GetItemsRequest(
    val userId: String? = null,
    val parentId: String? = null,
    val recursive: Boolean? = null,
    val includeItemTypes: List<ItemType>? = null,
    val excludeItemTypes: List<ItemType>? = null,
    val sortBy: List<ItemSortBy>? = null,
    val sortOrder: SortOrder? = null,
    val filters: List<ItemFilter>? = null,
    val fields: List<ItemField>? = null,
    val searchTerm: String? = null,
    val limit: Int? = null,
    val startIndex: Int? = null,
    val isFavorite: Boolean? = null,
    val mediaTypes: List<MediaType>? = null,
    val artistIds: List<String>? = null,
    val personIds: List<String>? = null,
    val studioIds: List<String>? = null,
    val genres: List<String>? = null,
    val tags: List<String>? = null,
    val years: List<Int>? = null,
    val ids: List<String>? = null,
    val enableImages: Boolean? = null,
    val imageTypeLimit: Int? = null,
    val enableUserData: Boolean? = null,
    val groupItems: Boolean? = null,
)
