package org.moonfin.server.core.model

enum class ItemType {
    MOVIE, SERIES, SEASON, EPISODE,
    AUDIO, MUSIC_ALBUM, MUSIC_ARTIST, MUSIC_VIDEO,
    PLAYLIST, PHOTO, PHOTO_ALBUM,
    BOX_SET, CHANNEL, PROGRAM,
    RECORDING, LIVE_TV_CHANNEL, LIVE_TV_PROGRAM,
    BOOK, TRAILER, VIDEO,
    PERSON, STUDIO, GENRE, MUSIC_GENRE,
    USER_VIEW, COLLECTION_FOLDER, FOLDER, BASE_PLUGIN_FOLDER,
    UNKNOWN
}
