package org.moonfin.server.core.model

enum class ItemSortBy {
    SORT_NAME, PREMIERE_DATE, DATE_CREATED, DATE_PLAYED,
    COMMUNITY_RATING, CRITIC_RATING, RUNTIME, PLAY_COUNT,
    RANDOM, OFFICIAL_RATING, INDEX_NUMBER, TRACK_NUMBER,
    ALBUM, ALBUM_ARTIST, ARTIST
}
