package org.moonfin.server.core.model

enum class ItemField {
    OVERVIEW, GENRES, MEDIA_SOURCES, MEDIA_STREAMS,
    PRIMARY_IMAGE_ASPECT_RATIO, CHAPTERS, CHILD_COUNT,
    DATE_CREATED, CHANNEL_INFO, CAN_DELETE, TAGLINES,
    PROVIDER_IDS, DISPLAY_PREFERENCES_ID, ITEM_COUNTS,
    MEDIA_SOURCE_COUNT, CUMULATIVE_RUN_TIME_TICKS, TRICKPLAY, PATH;
}
