package org.moonfin.server.core.model

import java.time.Instant

data class ServerItem(
    val id: String,
    val serverId: String?,
    val name: String,
    val originalTitle: String?,
    val type: ItemType,
    val mediaType: MediaType?,
    val overview: String?,
    val runTimeTicks: Long?,
    val premiereDate: Instant?,
    val productionYear: Int?,
    val officialRating: String?,
    val communityRating: Double?,
    val criticRating: Double?,
    val isFolder: Boolean,
    val parentId: String?,
    val seriesId: String?,
    val seriesName: String?,
    val seasonId: String?,
    val indexNumber: Int?,
    val parentIndexNumber: Int?,
    val imageTags: Map<ImageType, String>,
    val backdropImageTags: List<String>,
    val primaryImageAspectRatio: Double?,
    val userData: UserItemData?,
    val mediaSources: List<ServerMediaSource>?,
    val mediaStreams: List<ServerMediaStream>?,
    val container: String?,
    val channelId: String?,
    val channelName: String?,
    val people: List<ServerPerson>?,
    val genres: List<String>?,
    val tags: List<String>?,
    val studios: List<NameIdPair>?,
    val trickplay: Map<String, Any>? = null,
    val mediaSegments: List<Any>? = null,
)
